### ISSUE TITLE
Feature: Magic Link

### ISSUE THREAD

**Issue by iamclaytonray** [saas-js/saas-ui#1]
I saw auth as something being added in the future (or is in the paid option; i don't have access so don't know)

https://magic.link/ is super cool + super affordable, especially for early stage startups. I'm using in production and have a really positive experience with it. Just thought it was worth mentioning 🙂

**Comment by Pagebakers** [comment]
Thanks for the suggestion @iamclaytonray !

Auth is already available, although there is an issue with the Supabase service (the only build-in service currently). After that's fixed I will also publish the documentation for it.

I love using magic links for authentication, it's already supported through Supabase and is the default authentication type. You can see it in action here: https://storybook.saas-ui.dev/?path=/story/components-auth-auth--basic

I will add magic.link on the todo aswel.

**Comment by Pagebakers** [comment]
@iamclaytonray I went ahead and added Magic.link together with all other updates I had planned for authentication.

Check out the new docs here:
https://www.saas-ui.dev/docs/auth/auth-provider
and
https://www.saas-ui.dev/docs/auth/auth

Still some work to do on password auth, remember me and password reset functionality needs to be added.

Disclaimer, I didn't get around testing Magic.link yet.

Enable it like so:
```js
import { AuthProvider } from '@saas-ui/react'
import { createAuthService } from '@saas-ui/auth/services/magic-link'

// in your app root component
<AuthProvider {...createAuthService(magicClient)}>{children}</AuthProvider>
```

**Comment by iamclaytonray** [comment]
This is awesome! If I get some time today, I'll play around with it. I'm assuming contributions are welcome?

**Comment by Pagebakers** [comment]
Surething, I haven't set up any contribution guidelines yet. But help with bugfixes and improvements of any kind is really appreciated.

**Comment by iamclaytonray** [comment]
Found a few issues for Magic integration. Don't know if I can get a PR out today but I'll try 🙂

**Comment by Pagebakers** [comment]
@iamclaytonray Sorry about that, the Magic.link service wasn't exported correctly from the package. I've updated it in v0.7.1.

Just tested it and it's working beautifully. Have great weekend!
