### ISSUE TITLE
Feature: Allow pageSize prop to DataTable/DataGrid

### ISSUE THREAD

**Issue by iamclaytonray** [saas-js/saas-ui#107]
Currently, there's no way to allow for more than X amount of rows in DataTable/DataGrid. I propose we add a `pageSize` prop or maybe `rowsPerPage`

**Comment by Pagebakers** [comment]
Thanks for the feedback!

This is already supported thanks to React Table. You can set it on `initialState` , it actually supports most of the React Table properties.

The default is 20.

```ts
<DataGrid initialState={{pagination: {
        pageSize: 200,
      }}} />

**Comment by iamclaytonray** [comment]
Awesome, thanks!
