### ISSUE TITLE
Switch default value is ignored

### ISSUE THREAD

**Issue by jgillich** [saas-js/saas-ui#109]
Setting a default value on a switch `Field` does not work. Reproducible in the storybook: https://storybook.saas-ui.dev/?path=/story/components-forms-field--basic

The value defaults to true:

```js
defaultValues={{
      switch: true,
    }}
```

But it renders as false:

![Screenshot from 2022-12-17 15-06-06](https://user-images.githubusercontent.com/347965/208245879-48f9f041-44fb-4f2a-a34d-56d148f10745.png)

It's odd that `checkbox` works fine, as they're very similar.

**Comment by Pagebakers** [comment]
Thanks for reporting. Any idea why it is happening? 

Ill investigate asap

**Comment by Pagebakers** [comment]
Will be fixed in the next release.
