### ISSUE TITLE
Make NavItem Tooltip delay configurable

### ISSUE THREAD

**Issue by alexkreidler** [saas-js/saas-ui#110]
Currently, the `Tooltip` component in the `NavItem` has `openDelay={400}`, and there is no way to customize it. It would be great to have an option like `tooltipProps` in the `NavItemProps` to customize all the tooltip options.

Thanks for this great library!

**Comment by Pagebakers** [comment]
Thanks, thats a great idea 👌

Will add it to the next release

**Comment by Pagebakers** [comment]
Released!
