### ISSUE TITLE
[@saas-ui/theme-glass] Uncaught ReferenceError: process is not defined with Remix 

### ISSUE THREAD

**Issue by imcvampire** [saas-js/saas-ui#113]
When I try to use `@saas-ui/theme-glass`, Remix throws an error in client-side in these lines. There is no error with the main package.

```js
var __DEV__ = process.env.NODE_ENV !== "production";
var __TEST__ = process.env.NODE_ENV === "test";
```

**Comment by Pagebakers** [comment]
Do you have a full stack trace available?

**Comment by Pagebakers** [comment]
I found an issue with the build and released a new version.

Can you install 0.3.1 and try again?

**Comment by imcvampire** [comment]
Did you release 0.3.1? 

```No matching version found for @saas-ui/theme-glass@^0.3.1```

**Comment by Pagebakers** [comment]
Whoops, now it is!

**Comment by imcvampire** [comment]
Thank you. It's fixed!
