### ISSUE TITLE
Ability to provide custom Link component

### ISSUE THREAD

**Issue by imcvampire** [saas-js/saas-ui#115]
Is it possible if this library can provide an ability to provide a custom Link component? My use case is that I'm using Remix, and I need to use its component for all navigation, which is currently impossible.

**Comment by Pagebakers** [comment]
That's possible, although the api is not ideal, this will be improved in v2, since it was designed for the Next.js 12 Link component that doesn't render an element.

```tsx
const LinkComponent: React.FC<LinkProps> = (props) => {
  const {href, ...rest} = props
  if (React.isValidElement(props.children)) {
    return React.cloneElement(props.children, {
      as: Link, // remix Link
      to: href,
      ...rest
    })
  }
  return <>{props.children}</>
};

<SaasProvider linkComponent={LinkComponent} />
```

**Comment by imcvampire** [comment]
Nice, thank you for the solution!
