### ISSUE TITLE
Filter examples don't render

### ISSUE THREAD

**Issue by jgillich** [saas-js/saas-ui#118]
The filter examples don't work. Tested in both Firefox & Chrome

https://saas-ui.dev/docs/components/advanced-data/filters

![Screenshot from 2023-02-01 17-16-26](https://user-images.githubusercontent.com/347965/216102396-d0651bc5-317a-437e-9e79-1da682d518da.png)

**Comment by Pagebakers** [comment]
Looks like something went wrong with the deployment, will get it sorted asap.

You can find working examples in the storybook as well: https://storybook.saas-ui.pro/?path=/story/components-filters-activefilter--basic

**Comment by Pagebakers** [comment]
Fixed, an incompatible Chakra UI version was installed.
