### ISSUE TITLE
`label` for `confirmProps` is ignored

### ISSUE THREAD

**Issue by kculmback-eig** [saas-js/saas-ui#119]
When using `modals.confirm()`, `confirmProps.label` is ignored.

You can see an example in the Saas UI docs: https://saas-ui.dev/docs/components/overlay/modals-manager#open-a-confirm-dialog

`confirmProps.label` is set to `"Delete"`, but is being rendered as `"Confirm"`.

**Comment by jgillich** [comment]
Same with `SubmitButton`. Does the modal use it under the hood? It might be the same issue

```
<SubmitButton label="Foo"/>
// => Button saying 'Submit'
```

https://github.com/saas-js/saas-ui/commit/335acba93f3f9394e9c1345d8ecdf8fb0d28378a added a default for `Children`, which always overrides `label`.

**Comment by Pagebakers** [comment]
Thanks for reporting, will investigate tomorrow.

**Comment by Pagebakers** [comment]
Fixed in 1.8.3
