### ISSUE TITLE
Cannot configure noOfLines on ListItemLabel

### ISSUE THREAD

**Issue by ondraczsk** [saas-js/saas-ui#122]
Is it possible to modify noOfLines on ListItemLabel component? The default is 1 and I can't modify it, because it is styled on the span child (both primary and secondary label)

**Comment by Pagebakers** [comment]
Thanks for your feedback @ondraczsk !

If you use primary/secondary properties it adds noOfLines by default. I'm re-working this API in v2.

Using the label like this gives you more control for now.

```tsx
<StructuredListItemLabel>
 Label
</StructuredListItemLabel>
```
