### ISSUE TITLE
Switch field does not respond to default values

### ISSUE THREAD

**Issue by ismellike** [saas-js/saas-ui#123]
`<Field
    type="switch"
    name="simple_switch"
    />`
Setting defaultChecked or defaultValue to 1 | true | checked does not change the default value.
Setting isChecked or value to true does change the value, but then you cannot change the value.

**Comment by Pagebakers** [comment]
I ran some tests, but this is correct, defaultChecked isn't used in the Field since default values are handled by Form.

```ts
  <Form
    defaultValues={{
      switch: true,
    }}
    onSubmit={(values) => {
      console.log(values)
    }}
  >
      <Field name="switch" label="Switch" type="switch" />
</Form>
```
