### ISSUE TITLE
FormDialog: Type instantiation is excessively deep and possibly infinite.ts (2589)

### ISSUE THREAD

**Issue by ondraczsk** [saas-js/saas-ui#124]
I've got this error:
![image](https://user-images.githubusercontent.com/13401278/218969080-07bfd92f-9ccc-4ca0-a45a-08676ff9b329.png)
I've just copied this example from https://saas-ui.dev/docs/components/overlay/form-dialog. I've tried more examples from this page and every example throw this error. I have current version of saas-ui. Is it caused by version or anything else?

**Comment by Pagebakers** [comment]
Sometimes happens when there are multiple versions of a (chakra ui) package are installed. 

I'll try to reproduce this locally.

Which package manager do you use?

**Comment by Pagebakers** [comment]
I wasn't able to reproduce it yet. Could you share your tsconfig.json as well?

**Comment by ondraczsk** [comment]
Here are package versions
![image](https://user-images.githubusercontent.com/13401278/218974729-6913e503-701b-427a-b420-8668455ceef4.png)
And here tsconfig.json
https://pastebin.com/2pba97Tq

**Comment by Pagebakers** [comment]
Do you have the type issues also when removing ...yupForm?

**Comment by ondraczsk** [comment]
I don't know if its problem with that. Maybe it is something with the disclosure.
If I remove yupForm, error disappears, but then if I put fields into FormLayout manually, I get same error.
![image](https://user-images.githubusercontent.com/13401278/219125186-bcd00c4d-db89-46f9-84a8-e4dbb895c5d7.png)

Also, the code normally works and it renders without any problems, only error I have is in the VS Code.  I'm using workspace version, which is in my case 4.1.3
![image](https://user-images.githubusercontent.com/13401278/219126176-28b8b249-348d-4b34-bbbd-0c2b4134bbfe.png)

**Comment by Pagebakers** [comment]
@ondraczsk any luck fixing this issue?

**Comment by ondraczsk** [comment]
@Pagebakers yeah, sorry for not answering, it was problem with the version, now works like a charm :-)
