### ISSUE TITLE
`useSnackbar` is typed to returns an optional unnecessarily

### ISSUE THREAD

**Issue by tmoran-stenoa** [saas-js/saas-ui#125]
The return type of the function obtained via the `useSnackbar` hook is explicitly typed to return `ToastId | undefined`. The `undefined` part is unnecessary because the internal function used, `toast`, from Chakra UI, always returns `ToastId`.

This erroneous type annotation makes Typescript complain if we want to cancel or update a snackbar as the methods require a `ToastId`.

**Comment by Pagebakers** [comment]
Thanks @tmoran-stenoa, that is indeed incorrect. Will take this along in the v2 release.
