### ISSUE TITLE
Hidden menu dropdown of SelectField is causing a scrollbar to appear on smaller devices

### ISSUE THREAD

**Issue by tmoran-stenoa** [saas-js/saas-ui#126]
I have a SelectField in my page. Its hidden menu dropdown, which renders by default (though invisible) is stretching the page horizontally and creating a horizontal scrollbar on smaller devices (tablets and mobile devices).

You can see this in the video below:
1. There is extra white space at the right of the screen, which allows me to scroll horizontally.
2. When inspecting the dropdown in Chrome DevTools, we can see that the hidden dropdown is causing this extra space.
3. When first opening the dropdown, the latter adjusts to fit in the screen. So when the dropdown is closed, the problem is solved.

https://user-images.githubusercontent.com/84818024/221385967-15d9886e-b654-4856-adb3-56aab82ac9e0.mov

One way to solve this would be to add `isLazy` to the underlying `Menu`, however this is not possible through the `SelectField` component.

**Comment by Pagebakers** [comment]
I need to do some investigating with Chakra UI, but I believe the dropdown menu should automatically position itself left from the button in case it overflows the screen on the right side.

The Select will have an improved API in v2 to allow for better customization.

**Comment by Pagebakers** [comment]
I just tested this, the problem happens when the Select is added as the ListItem action, which is positioned absolute, and therefor the Menu position isn't calculated correctly.

This is already fixed in v2.

To fix it with 1.x you can add the Select as a child instead of action

```tsx
      <ListItem primary="Email" secondary="Receive a dialy email digest.">
            <Select name="test" options={[{ label: 'test', value: 'test' }]} />
          </ListItem>
```
