### ISSUE TITLE
`Select` menu dropdown cannot be wrapped in `Portal`

### ISSUE THREAD

**Issue by tmoran-stenoa** [saas-js/saas-ui#128]
Due to the implementation of the `Select` component, it is not possible to use a `Portal` with the menu dropdown. This means that the dropdown inherits styles from the parent, leading to the necessity for hacky work-arounds. It would be better to allow for the possibility of using a portal, say through a prop

**Comment by Pagebakers** [comment]
Good suggestion! I will take this along with redesigning the Select API.

**Comment by Pagebakers** [comment]
Fixed in 2.0
