### ISSUE TITLE
Vite 4.3 uses typescript 5 and breaks type imports

### ISSUE THREAD

**Issue by rkacenski** [saas-js/saas-ui#135]
When getting started with a fresh `npm create vite@latest` (4.3.1) project using react-ts, and flowing the Getting Started guide for Vite. Vscode was not detecting types properly:

```
Could not find a declaration file for module '@saas-ui/react'. '..../node_modules/@saas-ui/react/dist/index.modern.mjs' implicitly has an 'any' type.
  There are types at '...../node_modules/@saas-ui/react/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@saas-ui/react' library may need to update its package.json or typings.
```

However, this looks to be a TS5 issue.. so using vite@4.2 set up a project with TS 4.9, resolved the issue.

Not a blocker for me, but just thought it might be good to know.

**Comment by Pagebakers** [comment]
Thanks for letting me know, any idea why it might break?

**Comment by Pagebakers** [comment]
Just upgraded to TypeScript 5, and didn't run into any issues. 

I'm using Vite in storybooks, which runs OK too.

Could you share a repro that reproduces this?

**Comment by rkacenski** [comment]
Yup here you go:
https://github.com/rkacenski/saasui-ts5
I just spun up this repo in a code space with the same issue, here's a screenshot also.
![Screenshot 2023-05-02 at 2 09 45 PM](https://user-images.githubusercontent.com/773171/235786986-55cadb0d-ed13-4837-9e18-1e6e9090872c.png)

**Comment by Pagebakers** [comment]
Thanks a lot! Going to investigate.
