### ISSUE TITLE
Styles partially disappear for any component wrapped by <SaasProvider>

### ISSUE THREAD

**Issue by DevGJGlobal** [saas-js/saas-ui#144]
Hi, 

I first encountered the issue that the AppShell example taken [from here ](https://saas-ui.dev/docs/components/layout/app-shell#basic-shell) was rendering a blank page. 

To debug that I created a simple Create-Next-App with the default options, added Saas-UI dependencies in and just wrapped the default App component with SaasProvider tags. Some of the background disappeared.

#### Create Next App - Typescript
[CodeSandbox](https://codesandbox.io/p/github/DevGJGlobal/cna-ts-saas-ui-example/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cljx7vg49000g356n5metfgx9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cljx7vg48000b356nvyget55p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cljx7vg48000d356nm5zl74ra%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cljx7vg48000f356n5xw3kkg7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljx7vg48000b356nvyget55p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljx7vg47000a356nhl5wznz0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cljx7vg48000b356nvyget55p%2522%252C%2522activeTabId%2522%253A%2522cljx7vg47000a356nhl5wznz0%2522%257D%252C%2522cljx7vg48000f356n5xw3kkg7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljx7vg48000e356nz67oz23y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cljx7vg48000f356n5xw3kkg7%2522%252C%2522activeTabId%2522%253A%2522cljx7vg48000e356nz67oz23y%2522%257D%252C%2522cljx7vg48000d356nm5zl74ra%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljx7vg48000c356nqmyms7n2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cljx7vg48000d356nm5zl74ra%2522%252C%2522activeTabId%2522%253A%2522cljx7vg48000c356nqmyms7n2%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
[Github](https://github.com/DevGJGlobal/cna-ts-saas-ui-example)

#### Create Next App - Javascript
[CodeSandbox](https://codesandbox.io/p/github/DevGJGlobal/cna-js-saas-ui-example/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cljx82p3u000g356mfgwt5abd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cljx82p3t000b356mzu06svpu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cljx82p3t000d356m4928jlnb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cljx82p3t000f356md8h3jvqy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljx82p3t000b356mzu06svpu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljx82p3t000a356myrhfdc4w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cljx82p3t000b356mzu06svpu%2522%252C%2522activeTabId%2522%253A%2522cljx82p3t000a356myrhfdc4w%2522%257D%252C%2522cljx82p3t000f356md8h3jvqy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljx82p3t000e356mddwzcbcr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cljx82p3t000f356md8h3jvqy%2522%252C%2522activeTabId%2522%253A%2522cljx82p3t000e356mddwzcbcr%2522%257D%252C%2522cljx82p3t000d356m4928jlnb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljx82p3t000c356m9lmyj8z9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cljx82p3t000d356m4928jlnb%2522%252C%2522activeTabId%2522%253A%2522cljx82p3t000c356m9lmyj8z9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
[Github](https://github.com/DevGJGlobal/cna-js-saas-ui-example)

The same happened when a colleague tried Create React App. I'll add CRA to a repo also and share.

AppShell is also included in the index.tsx / index.js of these respective repos. You can comment out the default Create-Next-App index page and uncomment the AppShell example to see how it (doesn't) render.

**Edit:** I downgraded Next.JS 13 to 12 to see if that would fix it. All it seemed to do was now show the AppShell, but unstyled. (I can upload this example too if it would be useful). 
![image](https://github.com/saas-js/saas-ui/assets/127816255/4d6c216f-f740-4d82-9786-f1e8a62edbb9)

**Comment by DevGJGlobal** [comment]
Has anyone had any luck looking at the repos I've shared. The error is quite easily reproducible on CodeSandbox and I've attached screenshots in the respective Readme's too.

**Comment by Pagebakers** [comment]
I'm unable to access the code sandboxes. 

Can you try the following code? add       height="$100vh" to AppShell.

```ts
export default function Home() {
  return (
    <AppShell
      height="$100vh"
      navbar={
        <Box as="header" borderBottomWidth="1px" py="2" px="4">
        </Box>
      }
      sidebar={
        <Sidebar>
          <SidebarSection>
            <NavItem>Home</NavItem>
            <NavItem>Settings</NavItem>
          </SidebarSection>
        </Sidebar>
      }
    >
      <Box as="main" flex="1" py="2" px="4" overflowY="auto">
        Your application content
      </Box>
    </AppShell>
  )
}
```

**Comment by DevGJGlobal** [comment]
@Pagebakers Thanks for following up! 

I've updated the Codesandbox links - they should be accessible now. 
You should be able to see screenshots describing the issue on both Codesandbox and the Github repos linked above. 

> `Can you try the following code? add height="$100vh" to AppShell.`
Yes that fixes the height but does not solve the issue of the _default styles not being applied_

Based on [the documentation](https://saas-ui.dev/docs/components/layout/app-shell#basic-shell), I expect to see this:
![image](https://github.com/saas-js/saas-ui/assets/127816255/4f1f3791-e050-403d-ad73-e39f2ec338a1)

But I see this:
![image](https://github.com/saas-js/saas-ui/assets/127816255/206d2837-9e52-4849-9ddd-49f0b5662011)

Note: In both the repos the AppShell is commented out and at the bottom of the index.tsx (or index.js) file.

**Comment by Pagebakers** [comment]
That looks about right! Note that your theme probably renders in light mode by default, instead of the darkmode on the docs.

You can read more about how to setup dark/light mode here:
https://chakra-ui.com/docs/styled-system/color-mode

**Comment by DevGJGlobal** [comment]
I haven't had time to dig into the Chakra-UI color-mode yet, but do note this still doesn't solve the problem with NextJS 13 (which is what the linked repos and CodeSandbox are for), where the elements appear to have zero-size when using the AppShell template, and when using the default NextJS template, couple of the element/styles disappear (most of them are intact).

**Comment by Pagebakers** [comment]
I had to remove the css imports as they contain css resets that interfere with Chakra UI it seems.

[Code sandbox](https://codesandbox.io/p/github/DevGJGlobal/cna-ts-saas-ui-example/csb-wd7p5c/draft/agitated-gwen?file=%2Fpages%2F_document.tsx%3A11%2C25&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cljx7vg49000g356n5metfgx9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cljx7vg48000b356nvyget55p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cljx7vg48000d356nm5zl74ra%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cljx7vg48000f356n5xw3kkg7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B28.806207911949997%252C71.19379208805%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljx7vg48000b356nvyget55p%2522%253A%257B%2522id%2522%253A%2522cljx7vg48000b356nvyget55p%2522%252C%2522activeTabId%2522%253A%2522cljxzgs6500yk3b6n0qxt0xlm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljx7vg47000a356nhl5wznz0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpages%252Findex.tsx%2522%252C%2522id%2522%253A%2522cljxzfhml005o3b6nshaas0me%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpages%252F_app.tsx%2522%252C%2522id%2522%253A%2522cljxzgs6500yk3b6n0qxt0xlm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522SAVING%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpages%252F_document.tsx%2522%252C%2522id%2522%253A%2522cljxzhn8801h73b6n7f5gby1z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljx7vg48000f356n5xw3kkg7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljx7vg48000e356nz67oz23y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cljx7vg48000f356n5xw3kkg7%2522%252C%2522activeTabId%2522%253A%2522cljx7vg48000e356nz67oz23y%2522%257D%252C%2522cljx7vg48000d356nm5zl74ra%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljx7vg48000c356nqmyms7n2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cljx7vg48000d356nm5zl74ra%2522%252C%2522activeTabId%2522%253A%2522cljx7vg48000c356nqmyms7n2%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by DevGJGlobal** [comment]
That makes sense! Thank you!
