### ISSUE TITLE
BackgroundGradientRadial and BackgroundGradient rendering issue on Safari

### ISSUE THREAD

**Issue by Le0nX** [saas-js/saas-ui#145]
Right now the demo landing app and the official [saas-ui](saas-ui.dev) site don't work well on Safari. Rendering is very laggy. 

CPU usage grows dramatically up to 100% on macbook pro 2020 i7 32gb especially while scrolling. 

Google Chrome doesn't have these issues. 

After I've removed `getStaticProps` at the bottom of `index.tsx` performance issue has got better, but still not OK and worse than on Chrome.

UPD: after I've removed BackgroundGradientRadial and BackgroundGradient from landing, everything started working smoothly on Safari!

UPDUPD: I've turned off all blurs on gradients and navBar. Lags have gone.

**Comment by Pagebakers** [comment]
As mentioned on Discord, I made some changes that should trigger hardware acceleration in Safari, did it improve for you?
