### ISSUE TITLE
Unable to use Form in Remix.run

### ISSUE THREAD

**Issue by elcous** [saas-js/saas-ui#148]
Remix.run doesn't require onSubmit and handles all logic with action and method
Example:

<Form method="post" action="/events">

However in saas-ui, onSubmit is required and I am unable to use it in Remix

**Comment by elcous** [comment]
None of the elements can be used, because they all rely on Form wrapper

**Comment by Pagebakers** [comment]
Thanks for your feedback @elcous you can use the form components with remix using the `useSubmit` hook

https://remix.run/docs/en/main/hooks/use-submit

**Comment by elcous** [comment]
Also I wasn't able to get it to work with encType="multipart/form-data" for file uploads.

Can't wait until you release file uploads feature with drag/drop

Thank you
