### ISSUE TITLE
Remix.run log in confirmation page shows undefined

### ISSUE THREAD

**Issue by elcous** [saas-js/saas-ui#149]
Followed instructions to setup authorization. 

When using base setup with Remix, Supabase and MagicLink confirmation shows "underfined"

![Screenshot_8_24_23__7_27_PM](https://github.com/saas-js/saas-ui/assets/37813515/5995a2f6-8922-4510-adf8-9e127aa95600)

**Comment by Pagebakers** [comment]
Thanks this has been fixed in @saas-ui/auth@2.0.6
