### ISSUE TITLE
dateRangeInput its not exported

### ISSUE THREAD

**Issue by PedroHenriqueFernandes** [saas-js/saas-ui#150]
Hi!

The documentation [https://saas-ui.dev/docs/components/date-time/date-range-input/theming](url) says to import dateRangeInputAnatomy from `@saas/ui/anatomy`, but this file does not exist. Furthermore, looking at the file `packages/saas-ui-theme/src/anatomy/index.ts` I can't find the dateRangeInput.

Versions:
```
"@saas-ui/date-picker": "^0.10.6",
"@saas-ui/react": "^2.1.1",
"@saas-ui/theme": "^2.0.1",
```

**Comment by Pagebakers** [comment]
Thanks for reporting, this seems to be a mistake in the docs. The DatePicker isn't part of the Saas UI theme, so it's not supported yet.
