### ISSUE TITLE
Select fields' dropdown lists inside StepForms are invisible due to Chakra Collapse wrapper

### ISSUE THREAD

**Issue by adamstoffel** [saas-js/saas-ui#151]
When select fields are used inside a StepForm component, the dropdown lists (can be) mostly hidden due to the styling of the Chakra Collapse component having "overflow:hidden".

```typescript
<Field
  name="company_id"
  type="select"
  label="Company"
  options={companies.map((c) => ({ label: c.name, value: c.id }))}
/>
```

![image](https://github.com/saas-js/saas-ui/assets/2475873/d2142bde-6d8c-4ce5-9afb-00453cf35a86)
<img width="679" alt="image" src="https://github.com/saas-js/saas-ui/assets/2475873/d535a17d-effb-4fd3-affa-093953e3d39c">

**Comment by Pagebakers** [comment]
Thanks for reporting @adamstoffel, this is indeed an issue with the overflow and/or the select menu not opening in a portal.

It'd say it probably be best if the collapse doesn't get overflow hidden when it's open.

**Comment by adamstoffel** [comment]
@Pagebakers  Yeah looks good now. Thanks!
