### ISSUE TITLE
Filter Popover z-index issue

### ISSUE THREAD

**Issue by iamclaytonray** [saas-js/saas-ui#157]
I am using a DataGrid & Filters in a modal. Because filters are in a portal, I don't have a way to bring that popover up via z-index. Can we add options to `<FiltersAddButton />` to support adding styles to the popover?

**Comment by Pagebakers** [comment]
We can add `listProps` along with `buttonProps` for the time being. Will add this with other filters improvements I'm working on right now, expecting to release this early next week.

**Comment by iamclaytonray** [comment]
Okay. Thanks so much! Really appreciate the fast response!

**Comment by Pagebakers** [comment]
@iamclaytonray Just released 0.27.1 which now supports the listProps field so you can set the zIndex
