### ISSUE TITLE
ErrorBoundary does not invoke onError callback on SaasProvider

### ISSUE THREAD

**Issue by adamstoffel** [saas-js/saas-ui#158]
Per the docs (https://saas-ui.dev/docs/components/utils/error-boundary), the onError callback is supposed to be invoked when ErrorBoundary traps an error, however, the callback never executes.

When debugging, it appears that ErrorBoundary is attempting to this by calling `this.context.onError?.(error, errorInfo)`, but `this.context` is an empty object.

![image](https://github.com/saas-js/saas-ui/assets/2475873/ffcb4a16-1eaf-47e6-a1b0-b032fcf0a8a6)

**Comment by adamstoffel** [comment]
For context, this is my SaasProvider:

![image](https://github.com/saas-js/saas-ui/assets/2475873/1b6ffa6b-ce2b-4334-9413-11175e2aa580)

**Comment by adamstoffel** [comment]
Also created a CodeSandbox for this: https://codesandbox.io/p/sandbox/patient-grass-7mflxp

**Comment by Pagebakers** [comment]
Thanks for the reproduction, I found the issue. Will be fix in the next release.

**Comment by Pagebakers** [comment]
Should be fixed in 2.3.1, thanks again!
