### ISSUE TITLE
Zod and YupFormDialog do not perform validation onSubmit

### ISSUE THREAD

**Issue by adamstoffel** [saas-js/saas-ui#161]
It appears that the Zod and Yup Form Dialog components do not perform validation before invoking onSubmit.

You can test this in the [documentation page](https://saas-ui.dev/docs/components/overlay/form-dialog).

The Yup example makes 'title' require but this is not enforced. In the Zod example, adding `.nonempty()` or `.length(5)`, for example, is also not enforced.

**Comment by Pagebakers** [comment]
Thanks @adamstoffel validation doesn't seem to work properly indeed. Will investigate.

**Comment by adamstoffel** [comment]
Amazing, this is working for me with the new version. Thanks!
