### ISSUE TITLE
[DOCS] Add a CODE_OF_CONDUCT file to the repository

### ISSUE THREAD

**Issue by singodiyashubham87** [saas-js/saas-ui#163]
#### Problem or desire

The repository looks incomplete because of the missing CODE_OF_CONDUCT.md file to specify the rules and regulations to follow while contributing to the repository, I want to add that file to the repo.

#### Proposal

Add the CODE_OF_CONDUCT file to the repository with guidelines.

Kindly assign me this issue.

**Comment by singodiyashubham87** [comment]
@Pagebakers I want the project team's contact mail to be included in the CODE_OF_CONDUCT file.
Kindly provide me with the contact mail of this repository's maintenance team.

**Comment by Pagebakers** [comment]
You can add hello@saas-ui.dev thank you.
