### ISSUE TITLE
"Size" prop is not passed from command bar through from CommandBar to Chakra Modal

### ISSUE THREAD

**Issue by adamstoffel** [saas-js/saas-ui#179]
It would be helpful for building more complex command/search experiences if we could render a wider `CommandBar` element. The most obvious solution seems to use the "size" property on Chakra `Modal `but this isn't passed through from `CommandBar`.

It's also not possible to alter the size or appearance of the modal itself via style props because `CommandBar `doesn't accept an "sx" prop and the "container" style part is inside the modal.

**Comment by Pagebakers** [comment]
Thanks for the feedback @adamstoffel , that shouldn't be to hard to support, I will implement it 👍

**Comment by Pagebakers** [comment]
This is now available in 0.4.1. You can adjust the command dialog style using the CommandBarContent component.
