### ISSUE TITLE
Should use the `redirectUrl` instead of `redirectTo` prop to redirect the user after login

### ISSUE THREAD

**Issue by alexleetc28** [saas-js/saas-ui#186]
https://github.com/saas-js/saas-ui/blob/b601a8f67d7b1785f0a6039d5b92a10b40c77c5b/apps/website/src/pages/docs/components/authentication/auth/usage.mdx#L208

```
Error: Type '{ redirectTo: string; }' is not assignable to type 'IntrinsicAttributes & AuthProps'.
  Property 'redirectTo' does not exist on type 'IntrinsicAttributes & AuthProps'.ts(2322)
```

Should use `redirectUrl` instead.

**Comment by Pagebakers** [comment]
Thanks for reporting 👍

**Comment by Pagebakers** [comment]
Updated, thanks and merry christmas :)
