### ISSUE TITLE
Feature Request: Folder uploads on FileUpload component.

### ISSUE THREAD

**Issue by dadsgone0** [saas-js/saas-ui#199]
I'd like i have this feature for my cloud storage product. It's kinda annoying not being able to upload a folder.
It will also be helpful to my customers.

**Comment by Pagebakers** [comment]
This isn't fully supported in all browsers. At the moment not a priority to add such a feature, but you can experiment with these APIs to build the functionality:
https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry
