### ISSUE TITLE
Auth (password form) error message disappear immediately

### ISSUE THREAD

**Issue by fengkx** [saas-js/saas-ui#20]
randomly input non email in email input. click login and the message flash and disappear immediately

Seems only have this issue in dev mode (I am using Next.js)

**Comment by Pagebakers** [comment]
This is with Supabase I suppose?

**Comment by fengkx** [comment]
I am using supabase, Will it affect the popup error message?

**Comment by Pagebakers** [comment]
Could you make a short screencast showing the flash? I'm guessing it's the native browser validation error message.

You can disable this by adding the 'novalidate' property. It might be a good idea to add this by default to all forms.

**Comment by Pagebakers** [comment]
I did some tests and it seems like this is indeed the build in browser validation message.

You can either add novalidate to the  form.
```js
<Auth noValidate />

//or 

<AuthForm noValidate />
```

Or add a schema to the login, this allows you to add custom error messages as well.

```js

const passwordSchema = Yup.object({
  email: Yup.string().email('Invalid email address').required('Email is required').label('Email'),
  password: Yup.string().min(4).required().label('Password'),
})

<AuthForm type="password" action="logIn" resolver={yupResolver(schema)} />

**Comment by fengkx** [comment]
Today when I record the screencast, It doesn't flash(appear and disappear immediately) the popup tips jump doesn't show. But it will focus to email input without showing any error message.

https://user-images.githubusercontent.com/16515468/157679237-10bc96d0-acfd-4a7b-9b2c-0a734c497aaa.mp4

**Comment by fengkx** [comment]
https://user-images.githubusercontent.com/16515468/157679765-1359fbb4-6955-44b5-be03-01a767e64ca3.mp4

Here is the screencast of production build, to show what "popup error message" meaning
I expected the message show up for a while in both dev mode just like what it did in production build
