### ISSUE TITLE
Ability to clear date in DatePicker

### ISSUE THREAD

**Issue by heymartinadams** [saas-js/saas-ui#208]
### Description

Currently there’s no way to clear a date once it’s been set in the [DatePicker](https://saas-ui.dev/docs/components/date-time/date-picker).

### Saas UI Version

2.5.10

### Chakra UI Version

2.8.2

### Browser

Google Chrome 121

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
Could you go a bit more in details how you expect this to work, maybe with an example? When you use a controlled value you can reset it, but maybe that's not what you're looking for.
