### ISSUE TITLE
remove console.log in ConfirmDialog

### ISSUE THREAD

**Issue by alexleetc28** [saas-js/saas-ui#211]
### Description

https://github.com/saas-js/saas-ui/blob/d35ae5ae7f8cc9627e8eda7a3f6ecd208cff7969/packages/saas-ui-modals/src/dialog.tsx#L108

### Saas UI Version

2.6.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
Thanks! Will be removed in the next release.
