### ISSUE TITLE
asynchronous custome theme

### ISSUE THREAD

**Issue by tienhoangkhmt** [saas-js/saas-ui#216]
### Description

I'm using the pro package, I want to synchronize the colors between the pro and free versions, how do I do that??
I used withDefaultColorScheme to set default colors for the project but it seems like I only get the pro version and the free version doesn't work.
My code is based on your base

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Saas UI Version

2

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by tienhoangkhmt** [comment]
I don't understand what you are saying

**Comment by Pagebakers** [comment]
Closing this in favour of our thread in discord.
