### ISSUE TITLE
StructuredList: Keyboard Accessibility

### ISSUE THREAD

**Issue by bhainesva** [saas-js/saas-ui#218]
### Description

When I made a StructuredListItem interactive by specifying an `href` or `onClick` property, I expected to be able to navigate to and trigger those items using the keyboard but it seems like they only become accessible via keyboard if they're first interacted with using the mouse.

### Link to Reproduction

[https://codesandbox.io/p/sandbox/elegant-microservice-8sjlcy](https://codesandbox.io/p/sandbox/elegant-microservice-8sjlcy)

### Steps to reproduce

1. Go to [https://codesandbox.io/p/sandbox/elegant-microservice-8sjlcy](https://codesandbox.io/p/sandbox/elegant-microservice-8sjlcy)
2. Click to focus on the preview pane
3. Use tab, shift+tab to navigate the document with the keyboard, notice that list items cannot receive focus
4. Click on one of the list items (triggering its onclick)
5. Try using keyboard navigation again, see that the items can now receive focus.

### Saas UI Version

2.7.4

### Chakra UI Version

2.8.2

### Browser

Firefox 124.0.2 (64-bit), Chrome Version 123.0.6312.124 (Official Build) (x86_64), Safari Version 15.4 (17613.1.17.1.6)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![slist](https://uploads.linear.app/14807ff2-55c5-44c9-9588-135c961250cc/25082738-1c3d-4b91-a2a8-6cb45cb957af/b1472f07-ff4a-48b6-a607-d2f075ec866d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE0ODA3ZmYyLTU1YzUtNDRjOS05NTg4LTEzNWM5NjEyNTBjYy8yNTA4MjczOC0xYzNkLTRiOTEtYTJhOC02Y2I0NWNiOTU3YWYvYjE0NzJmMDctZmY0YS00OGI2LWE2MDctZDJmMDc1ZWM4NjZkIiwiaWF0IjoxNzEzMzUwMzU1LCJleHAiOjMzMjgzOTEwMzU1fQ.lm3QvXRtcHqmcAuZhBbreTEhDr64T40zC4HeKpKnG_8)

**Comment by Pagebakers** [comment]
Thanks for the reproduction. It seems like the tab indexes on the items are set incorrectly. Will look for a fix tomorrow.

**Comment by Pagebakers** [comment]
@bhainesva Fixed keyboard navigation in the PR above. This will be released shortly.
