### ISSUE TITLE
Yarn install fails

### ISSUE THREAD

**Issue by willopez** [saas-js/saas-ui#22]
Hello, I attempted to install the dependencies and got this error after deleting the `yarn.lock` and starting fresh, because the included `yarn.lock` was generating a similar error.

```
 YN0041: │ @saas-ui/next-workspaces@npm:^0.1.1: Invalid authentication (as an anonymous user)
➤ YN0000: └ Completed in 0s 751ms
➤ YN0000: Failed with errors in 0s 756ms
```

It seems that a private npm module is being requested for which the public does not have access.

**Comment by Pagebakers** [comment]
Thanks for the feedback @willopez 

Are you running this from a fork of the repository?

**Comment by willopez** [comment]
Commenting out those lines helped and I also needed to remove `"@saas-ui/pro": "^0.2.0",` from the website `package.json`. I belive that is a private package.

**Comment by Pagebakers** [comment]
Great! It’s private indeed. I’m looking into how I can include the premium components into the docs. I might actually make it work with module federation, so we don’t run into these issues.

**Comment by willopez** [comment]
Sounds good and great job on this projects, looks great :)

**Comment by Pagebakers** [comment]
Thanks, appreciate 🙏
