### ISSUE TITLE
ContextMenu disables the onClick of the component its applied on

### ISSUE THREAD

**Issue by haroonriaz-15** [saas-js/saas-ui#229]
### Description

When I applied contextMenu over a box, the OnClick function of the box is not working anymore. I disabled long press gesture but the issue still persists

### Steps to reproduce

1. Create a Box from Chakra UI and add onClick function on it'
2. Add ContextMenu over it
3. Now Left Click on the box
4. The onClick won't be triggered

### Saas UI Version

2.6.2

### Chakra UI Version

2.8.2

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
Please try in latest (2.8.3), I released a couple of fixes in 2.8.2 regarding context menu.
