### ISSUE TITLE
Checkbox label is rendered twice

### ISSUE THREAD

**Issue by Pima-Dev** [saas-js/saas-ui#233]
### Description

Field of type checkbox has label rendered twice. The label should only be displayed to the right of the checkbox

Actual :
![image](https://github.com/saas-js/saas-ui/assets/28201009/39cd496f-874d-473e-a4ea-c419e2c2cdd0)

Expected :
![image](https://github.com/saas-js/saas-ui/assets/28201009/3d5b269f-41ce-4fa2-800f-18cdf284d587)

### Link to Reproduction

https://saas-ui.dev/docs/components/forms/field#checkbox-field

### Saas UI Version

2.8.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
Thanks for reporting!

**Comment by Pagebakers** [comment]
Will be fixed in the next release.

**Comment by Pima-Dev** [comment]
Fixed in 2.8.5, thanks!
