### ISSUE TITLE
DateInput storybook error

### ISSUE THREAD

**Issue by bhainesva** [saas-js/saas-ui#239]
### Description

The story here is throwing an error: https://storybook.saas-ui.dev/?path=/story/components-datetime-dateinput--date-time. 

`Invalid granularity minute for value 2023-01-01`
<img width="1358" alt="image" src="https://github.com/saas-js/saas-ui/assets/6308571/723cf379-55a6-488b-a8e4-9844d7775150">

### Link to Reproduction

https://storybook.saas-ui.dev/?path=/story/components-datetime-dateinput--date-time

### Steps to reproduce

1. Go to https://storybook.saas-ui.dev/?path=/story/components-datetime-dateinput--date-time

### Saas UI Version

whatever the storybook is using

### Browser

Firefox 127.0.1 (64-bit)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
Thanks for the heads up!

**Comment by Pagebakers** [comment]
Fixed!
