### ISSUE TITLE
Tooltip Customization

### ISSUE THREAD

**Issue by gautomdas** [saas-js/saas-ui#255]
### Description

It's hard to control the styling for the tooltip in SaasUI charts. Rather then reimplementing the tooltip and then passing that prop, it'd be easier the the ChartTooltip component was also exported along side some props to make it easier to create custom tool tips based off the original one.

Would you guys be open to that simple fix or I don't mind submitting a PR myself.

### Saas UI Version

2.5.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
@gautomdas feel free to open a PR that exports the component, much appreciated.
