### ISSUE TITLE
Chart Tooltip Doesn't Allow for Theming

### ISSUE THREAD

**Issue by benmcginnis** [saas-js/saas-ui#257]
### Description

We have a custom tooltip theme that uses a dark background, but because the tooltip explicitly sets the "muted" token for the [color of the metric name via a prop](https://github.com/saas-js/saas-ui/blob/08e841c9a69cc4ba08a6b4c61a8d4e5cc75cbbdc/packages/saas-ui-charts/src/tooltip.tsx#L72), we can't easily override the theming, leading to unreadable text.  

See screenshot:
![image (8)](https://github.com/user-attachments/assets/9a3268be-ecd8-4531-b408-2bb9cbeacb9c)

Can this be refactored into a theme setting rather than using a style prop?

Version number of charts is 0.11.3

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Saas UI Version

2.8.8

### Chakra UI Version

2.8.2

### Browser

Arc 1.59 (Chromium 128)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
This element is not part of the Tooltip theme.

Will change this to use a css variable `color="var(--tooltip-fg-muted, var(--chakra-colors-muted))"` that you can overwrite in the theme.
