### ISSUE TITLE
Metadata problem

### ISSUE THREAD

**Issue by aydinws** [saas-js/saas-ui#261]
### Description

app/(marketing)/page.tsx
Type error: Page "app/(marketing)/page.tsx" does not match the required types of a Next.js Page.
  "meta" is not a valid Page export field.

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Saas UI Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
Where exactly do you get this error?

The export name should be `metadata`

**Comment by danias** [comment]
The export name cannot be metadata in a client file
