### ISSUE TITLE
Modals don't seem to be exported

### ISSUE THREAD

**Issue by siphosenkosindhlovu** [saas-js/saas-ui#262]
### Description

Everything in `@saas-ui/modals`  doesn't seem to be exported anymore and I get Typescript errors when trying to import `ModalsProvider`, `createModals` and `useModals`

### Steps to reproduce

1. Import anything dependant on @saas-ui/modals.
2. Get a `Module @saas-ui/react has no exported member [module name].

### Saas UI Version

2.10.1

### Chakra UI Version

2.10.3

### Browser

Microsoft Edge 129

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
What `moduleResolution` do you use in your tsconfig?

**Comment by Pagebakers** [comment]
I found the issue, it was an incorrect typesVersions config in package.json of the modals packages. Fixed in 2.10.3

Alternatively you can also set moduleResolution to bundler.

**Comment by siphosenkosindhlovu** [comment]
> What `moduleResolution` do you use in your tsconfig?

I'm using `node`, but it was working up until a few days ago.

**Comment by siphosenkosindhlovu** [comment]
> I found the issue, it was an incorrect typesVersions config in package.json of the modals packages. Fixed in 2.10.3
> 
> Alternatively you can also set moduleResolution to bundler.

Thank you.

**Comment by Pagebakers** [comment]
Thanks a lot for the sponsorship ❤️
