### ISSUE TITLE
DataTable does not inherint TableOptions props

### ISSUE THREAD

**Issue by waptik** [saas-js/saas-ui#30]
As the title says, the DataTable components have not inherited props from TableOptions such as `columns, data` according to vscode's typescript IntelliSense.
I copied example code from https://www.saas-ui.dev/docs/data-display/data-table#typescript
![image](https://user-images.githubusercontent.com/1687551/159951909-98cf8172-3ff0-48ae-9f8c-be22786ba2bd.png)

I thought it was because of types issues regarding columns, so I removed them but the error still persisted
![image](https://user-images.githubusercontent.com/1687551/159952325-4c56f379-cd3c-4651-af0d-6a917ce971ca.png)

Removing `columns` from `DataTable` now shows that prop `data` does not exist
![image](https://user-images.githubusercontent.com/1687551/159952651-b8004432-3cb9-409c-ad52-7be9a11f80ef.png)

Type error disappears after removing all props

![image](https://user-images.githubusercontent.com/1687551/159958510-80423098-4335-47f0-8c22-f7b8defa8f9d.png)

**Comment by Pagebakers** [comment]
Are you importing `Column` from react-table or from `@saas-ui/react` ?

**Comment by waptik** [comment]
Yes, i am

**Comment by Pagebakers** [comment]
Can you post the contents of this file in a gist? I'll try to run it here to get a better understanding.

**Comment by Pagebakers** [comment]
Can't reproduce it here on my machine, it's not giving any issues.

<img width="623" alt="Screenshot 2022-03-24 at 20 01 47" src="https://user-images.githubusercontent.com/32583/160000412-111c35a2-033b-4251-93b0-72209c621f2c.png">

**Comment by Pagebakers** [comment]
Here's a complete working example.
```ts

import { DataTable, Column, DataTableCell } from '@saas-ui/react'

interface Data {
  id: string
  country: string
  sales: number
  revenue: string
  metrics: number[]
}

const data: Data[] = [
  {
    id: 'us',
    country: 'US',
    sales: 454433,
    revenue: '€244543,-',
    metrics: [10, 20, 15, 22, 30, 40, 26],
  },
  {
    id: 'nl',
    country: 'Netherlands',
    sales: 3232,
    revenue: '€54432,-',
    metrics: [10, 20, 15, 22, 30, 40, 26],
  },
  {
    id: 'Germany',
    country: 'Germany',
    sales: 2343,
    revenue: '€34842,-',
    metrics: [10, 20, 15, 22, 30, 40, 26],
  },
]

const columns: Column<Data>[] = [
  {
    id: 'country',
    Header: 'Country',
  },
  {
    id: 'sales',
    Header: 'Sales',
    isNumeric: true,
  },
  {
    id: 'revenue',
    Header: 'Revenue',
    isNumeric: true,
  },
  {
    id: 'metrics',
    Header: '',
    width: '5%',
    Cell: MetricsCell,
  },
]

export const SalesByCountry = () => {
  return (
    <DataTable<Data> columns={columns} data={data} />
  )
}
```

**Comment by Pagebakers** [comment]
Did you add this to your project?

https://github.com/saas-js/saas-ui/blob/main/apps/website/src/types/react-table-config.d.ts

**Comment by waptik** [comment]
> Did you add this to your project?
> 
> [https://github.com/saas-js/saas-ui/blob/main/apps/website/src/types/react-table-config.d.ts](https://github.com/saas-js/saas-ui/blob/main/apps/website/src/types/react-table-config.d.ts?rgh-link-date=2022-03-24T20%3A07%3A06Z)

Yup, I did. In my `types/` folder as ``

> Can't reproduce it here on my machine, it's not giving any issues.
> 
> <img alt="Screenshot 2022-03-24 at 20 01 47" width="623" src="https://user-images.githubusercontent.com/32583/160000412-111c35a2-033b-4251-93b0-72209c621f2c.png">

That's weird. Is the my tsconfig the issue then?

**Comment by Pagebakers** [comment]
Looks good to me, can you add the imports you're using too? 

This is the DataTableProps type by the way, only thing I can think of other then this is that `@types/react-table` isn't installed in your project for some reason. Should be installed with @saas-ui out of the box. 

Can you try to add it to your project?

```
yarn add -D @types/react-table
```

```
export interface DataTableProps<Data extends object>
  extends TableOptions<Data> {
  /**
   * Enable sorting on all columns
   */
  isSortable?: boolean
  /**
   * Enable row selection
   */
  isSelectable?: boolean
  /**
   * Triggers whenever the row selection changes.
   * @returns {string[]}
   */
  onSelectedRowsChange?: (rows: IdType<Data>[]) => void
}
```

**Comment by waptik** [comment]
> Looks good to me, can you add the imports you're using too?
> 
I updated my gist with my imports

> This is the DataTableProps type by the way, only thing I can think of other then this is that `@types/react-table` isn't installed in your project for some reason. Should be installed with @saas-ui out of the box.
> 

For some odd reason wasn't installed with saas-ui out of the box.
![image](https://user-images.githubusercontent.com/1687551/160100090-46d18331-4ac8-4ea1-9ab3-7e9a8c66312c.png)

> Can you try to add it to your project?
> 
> ```
> yarn add -D @types/react-table

Before using `yarn add -D @types/react-table`, I first uninstalled saas-ui and reinstalled it again but couldn't find `@types/react-table` in `node_modules/*`. I wonder if that should be the case.
I've now manually installed it and it's all good now.

**Comment by waptik** [comment]
Final notes, i think there should be ways to extends `DataTable` so that users can setup **filtering, pagination, etc.** . Right now, the best way to achieve that is copy the code at https://github.com/saas-js/saas-ui/blob/main/packages/saas-ui-data-table/src/data-table.tsx and manually do changes.

**Comment by Pagebakers** [comment]
Thanks for the info! It might be that Yarn 1.22 isn't installing the dev dependencies.
I'm using Yarn 3, so that would explain why I can't reproduce it. I will add a note in the docs.

Being able to easily extend it would be great indeed, I'm not sure yet how that would work. I'll let this sit for a while to think about it.

**Comment by Pagebakers** [comment]
It might be possible to do something like this.

```tsx
<DataTable columns={columns} data={data} plugins={[useFilters, usePagination]}>
  <TableBody>
  {({page}) => {
    return page.rows.map((row) => <TableRow {...row} />)
   }}
  </TableBody>
</DataTable>
```

There's quite some work involved to make this happen, so it won't make it into the 1.0 release for now. But will add this to the roadmap.
