### ISSUE TITLE
Auth LoginForm read "logIn" property for undefined

### ISSUE THREAD

**Issue by fengkx** [saas-js/saas-ui#32]
![image](https://user-images.githubusercontent.com/16515468/162630376-c91f1a48-c0d2-4975-b7e6-ee9070980841.png)
![image](https://user-images.githubusercontent.com/16515468/162630447-34e49d44-d61b-41cd-b6c6-a5e11f07afed.png)

**Comment by Pagebakers** [comment]
Thanks for reporting.

Which auth service are you using?
 
Can you share your `<AuthProvider />` code?

**Comment by Pagebakers** [comment]
Actually this error is probably because you haven't setup the auth provider, see: https://www.saas-ui.dev/docs/auth/auth-provider#setup-authprovider

**Comment by fengkx** [comment]
![image](https://user-images.githubusercontent.com/16515468/162630850-c692ba40-d356-4ab8-a2bc-4267b58cb4b1.png)
![image](https://user-images.githubusercontent.com/16515468/162630868-7a1ecef0-ada1-4246-abc2-a7984c486fb7.png)

I have setup this for a while.  I just have a dependencies updated 0.6.5 -> 0.7.3

**Comment by Pagebakers** [comment]
Thanks, I'll investigate this.

**Comment by Pagebakers** [comment]
Did you upgrade both @saas-ui/react and @saas-ui/auth to the latest version?

**Comment by fengkx** [comment]
Yes, I upgrade both of them

**Comment by Pagebakers** [comment]
I'm unable to reproduce this unfortunately.

Can you share some more information.

Node version / React version / Chakra UI version / Saas ui versions.

**Comment by Pagebakers** [comment]
Finally managed to reproduce it, looking into it.

**Comment by Pagebakers** [comment]
Ok my suspicion was right.

This happens when you manually add @saas-ui/auth to your package.json and the versions aren't in sync. If you project uses 2 different auth versions the AuthProvider context will break.

```
"@saas-ui/auth": "^0.7.4",
"@saas-ui/react": "^0.12.8",
```

You can check your lockfile to see if there are multiple versions of /auth installed.

If the problem persists I recommend removing node_modules and run install again.

**Comment by fengkx** [comment]
![image](https://user-images.githubusercontent.com/16515468/163425539-661a365e-b60e-40f5-8321-416327d50c03.png)
There are multiple versions of /auth. 

Thanks for your hard work.
https://www.saas-ui.dev/docs/integrations/supabase The document has a import from auth package. How could I keep the two package in sync?
