### ISSUE TITLE
BannerCloseButton is irresponsive

### ISSUE THREAD

**Issue by waptik** [saas-js/saas-ui#53]
When you go to https://www.saas-ui.dev/docs/feedback/banner#usage and click the `X` icon, nothing happens.

It also happens when you use it in your code. Some other close buttons seem to also be irresponsive but i don't remember which ones.

**Comment by Pagebakers** [comment]
That's correct it needs to be controlled, so you need to add isOpen / onClose / onOpen props with `useDisclosure` for example.

**Comment by waptik** [comment]
Oh, I see! I saw an example over at https://www.saas-ui.dev/docs/feedback/banner#transitions. Now I understand
Thanks
