### ISSUE TITLE
Cannot find module '@saas-ui/forms/zod' or its corresponding type declarations

### ISSUE THREAD

**Issue by waptik** [saas-js/saas-ui#58]
After upgrading to version `1.0.1` from `1.0.0-rc.15`, I'm no longer able to import `zodFieldResolver, zodResolver` from `@saas-ui/forms/zod`.
This is how i was using it
```tsx
// BaseForm.tsx
import { zodFieldResolver, zodResolver } from "@saas-ui/forms/zod";
import { Form as BaseForm } from "@saas-ui/react";
import { ZodTypeAny } from "zod";

BaseForm.getResolver = (schema: ZodTypeAny) => zodResolver(schema); // @hookform/resolvers
BaseForm.getFieldResolver = (schema: ZodTypeAny) => zodFieldResolver(schema); // AutoForm field resolver

export default BaseForm;
```

UPDATE: this issue always happens when I upgrade `@saas-ui/react` to the latest released version. Even if I revert back to the previous version after that, the problem still persists. So I delete `node_modules` and `yarn.lock` then I do a fresh installation of packages inside `package.json`

**Comment by Pagebakers** [comment]
I just upgraded my test project and don't have issues with the import, it might have something to do with where yarn is saving the package folders.

Adding @saas-ui/forms as a dependency to your project should make sure the references are correct.

**Comment by waptik** [comment]
> I just upgraded my test project and don't have issues with the import, it might have something to do with where yarn is saving the package folders.
> 
> Adding @saas-ui/forms as a dependency to your project should make sure the references are correct.

Thanks, that's what I'm doing for now.
It seems like yarn is installing `@saas-ui` dependencies under `@saas-ui/react/node_modules/@saas-ui`
![image](https://user-images.githubusercontent.com/1687551/177016506-a3d6efff-9642-4b32-be3d-75e1ffb2a7c0.png)

**Comment by waptik** [comment]
So after installing the forms packages, i'm getting the error as seen below. Did i import the wrong resolver?
For now, I 'm using `ts-ignore` to make it go away.

![image](https://user-images.githubusercontent.com/1687551/177029650-730db7c6-4a14-4c96-b97a-e37647ddfc59.png)

Full version:
```ts
Type '(schema: ZodTypeAny) => <TFieldValues extends FieldValues, TContext>(values: TFieldValues, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => Promise<...>' is not assignable to type 'GetResolver'.
  Type '<TFieldValues extends FieldValues, TContext>(values: TFieldValues, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => Promise<...>' is not assignable to type '<TFieldValues extends FieldValues, TContext>(values: UnpackNestedValue<TFieldValues>, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => Promise<...>'.
    Types of parameters 'options' and 'options' are incompatible.
      Type 'ResolverOptions<TFieldValues>' is not assignable to type 'ResolverOptions<UnpackNestedValue<TFieldValues>>'.
        Types of property 'names' are incompatible.
          Type 'FieldName<TFieldValues>[] | undefined' is not assignable to type 'FieldName<UnpackNestedValue<TFieldValues>>[] | undefined'.
            Type 'FieldName<TFieldValues>[]' is not assignable to type 'FieldName<UnpackNestedValue<TFieldValues>>[]'.
              Type 'FieldName<TFieldValues>' is not assignable to type 'FieldName<UnpackNestedValue<TFieldValues>>'.
                Type 'string | Extract<keyof TFieldValues, string>' is not assignable to type 'FieldName<UnpackNestedValue<TFieldValues>>'.
                  Type 'string' is not assignable to type 'FieldName<UnpackNestedValue<TFieldValues>>'.ts(2322)
```

**Comment by Pagebakers** [comment]
Did you solve it? or still using @ts-ignore?

**Comment by waptik** [comment]
Still using ts-ignore

**Comment by Pagebakers** [comment]
Ok let's re-open. 

I wasn't able to reproduce this, but I did see there was a breaking change in a minor version of hook form resolvers that could be related.

**Comment by waptik** [comment]
Oh, I see! I'll keep an eye on this issue then.

**Comment by Pagebakers** [comment]
Which versions of react-hook-form and @hookform/resolver do you have installed?

**Comment by waptik** [comment]
> Which versions of react-hook-form and @hookform/resolvers do you have installed?

I haven't installed any of them. I'm using the one that comes with `saas-ui` as seen in the initial comment

**Comment by Pagebakers** [comment]
I will release a fix to support the latest the breaking change.

**Comment by Pagebakers** [comment]
Fixed in 1.0.2 

Thanks again!

**Comment by waptik** [comment]
> Fixed in 1.0.2
> 
> Thanks again!

I can confirm that the issue has been fixed in v1.0.2 👌

**Comment by waptik** [comment]
So i'm commenting again because i found something weird about how yarn v3 installs packages.
Yarn installs packages differently when using workspaces as compared to when you are not.

I tried with two examples: the workspace + turborepo monorepo is at https://github.com/waptik/turborepo-saas-ui-basic-example and the non-monorepo example, you check [these steps](https://github.com/saas-js/saas-ui/issues/66#issuecomment-1179494578).
- For the monorepo, yarn install some of `saas-ui` packages in `node_modules/@saas-ui` and the rest under `node_modules/@saas-ui/react/node_modules/@saas-ui`

![node_modules/@saas-ui/react](https://user-images.githubusercontent.com/1687551/178117789-38374921-59be-47d0-832a-c960383a6d36.png)
![node_modules/@saas-ui/react/node_modules/@saas-ui](https://user-images.githubusercontent.com/1687551/178117809-f3bcc175-ce4f-4dfa-9fba-cb7d54f1dd04.png)

- And for non-monorepo app, all the packages are directly under `node_modules/@saas-ui` and no extra `node_modules/@saas-ui/react/node_modules/@saas-ui`. That's why `@saas-ui/forms` needs to be re-installed separetely
![node_modules/@saas-ui](https://user-images.githubusercontent.com/1687551/178117649-7098778e-8ba5-4e3c-ac03-7918d9305a23.png)
![node_modules/@saas-ui/react/node_modules/@saas-ui](https://user-images.githubusercontent.com/1687551/178117727-6c0f7fc6-9f12-4447-b216-004780e21081.png)

My question is, is that functionality from yarn or turborepo itself?

**Comment by Pagebakers** [comment]
Thats correct, that's why you have to add specific sub packages to your package.json otherwise they might not resolve correctly.

Eg if you import from @saas-ui/forms you need to add this package together with @saas-ui/react. Same for /auth, etc.

**Comment by waptik** [comment]
That's really stressful. Does pnpm solve that issue?

**Comment by Pagebakers** [comment]
I dont think so. Almost everything is re-exported from @saas-ui/react , as long as you import from there it shouldn't cause any issues.

Only for the form resolvers and auth services you need to import from /forms and /auth and thus add these to your package.json 

I might make sense though to create separate packages for the resolvers and auth services as it can cause problems like in your other issue when package versions are not in sync.

**Comment by waptik** [comment]
> I dont think so. Almost everything is re-exported from @saas-ui/react , as long as you import from there it shouldn't cause any issues.

I see, I thought it did. It's a good thing that the majority of components can be directly accessed through `@saas-ui/react`
> Only for the form resolvers and auth services you need to import from /forms and /auth and thus add these to your package.json

I think it'd be great to put a notice somewhere in the docs about this issue(installing in monorepo vs non-monorepo) so that you don't get other users asking the same question over again.

>It might make sense though to create separate packages for the resolvers and auth services as it can cause problems like in your other issue when package versions are not in sync.

Yeah you're right. It was a pain with another issue and fortunately, I managed to fix it.

Thanks for everything.
