### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by Pagebakers** [saas-js/saas-ui#6]
Tests for all packages

- [x] Test a11y in all packages.
- [x] auth
- [x] banner
- [x] button
- [x] card
- [x] collapse
- [x] data-table
- [x] forms
- [x] hooks
- [x] hotkeys
- [x] input-right-button
- [x] layout
- [x] list
- [x] context-menu (menu package)
- [x] modals
- [x] nprogress
- [x] number-input
- [x] palette
- [x] password-input
- [x] persona
- [x] pin-input
- [x] property
- [x] provider
- [x] radio
- [x] search-input
- [x] select
- [x] snackbar
- [x] web3

**Comment by elcharitas** [comment]
I would like to write some tests. Prolly would be making a pr for this?
@Pagebakers

**Comment by Pagebakers** [comment]
@elcharitas Oh this would be really amazing, any help is highly appreciated!

**Comment by Pagebakers** [comment]
> I would like to write some tests. Prolly would be making a pr for this? @Pagebakers

Still want to help with this?

I started freeing up time for this, as this is the last stretch for the release candidate, but could def use some extra hands.

**Comment by elcharitas** [comment]
Yes I def want to 💯 . It's a matter of getting a format of how you would want the tests to be
