### ISSUE TITLE
Typos in copy - 'build on' should be 'built on'

### ISSUE THREAD

**Issue by TomJPrice** [saas-js/saas-ui#60]
Hi, awesome work so far - looks great.

Noticed a few instances where the grammatically correct term would be 'built on' but the term used has been 'build on'.

For example, inside `apps/website/src/pages/index.tsx`, `line 731`: 

> Saas UI is build on top of <Em>Chakra UI</Em>

This same grammatical error can be seen in your footer. Best of luck with this project - I will be sure to give SaaS UI a try in the near future! 👍 

<img width="663" alt="Screenshot 2022-07-05 at 11 12 28" src="https://user-images.githubusercontent.com/64794620/177305563-9c91e783-ad2b-4967-bbc9-78976c7116ab.png">
<img width="613" alt="Screenshot 2022-07-05 at 11 12 44" src="https://user-images.githubusercontent.com/64794620/177305572-c42e9f02-373e-4bb4-874c-94200a710a52.png">

**Comment by Pagebakers** [comment]
Thanks Tom! 

That is awkward 😅, I only notice it now that you mention it. 

I'll get this sorted asap.
