### ISSUE TITLE
ContextError: useStepFormContext: `context` is undefined

### ISSUE THREAD

**Issue by waptik** [saas-js/saas-ui#66]
Hi again! I kinda have this weird issue with `useStepFormContext`  in localhost. I tried using the code from https://github.com/saas-js/saas-ui/discussions/51#discussioncomment-3021816 but I'm getting this error: 
```sh
`ContextError: useStepFormContext: `context` is undefined. Seems you forgot to wrap step form components in `<StepForm />`
```
The weird part is that the same code works on codesandbox. Here is the [Sandbox](https://codesandbox.io/s/tender-bird-6xnsx4?file=/pages/onboarding.tsx) and the [demo](https://6xnsx4.sse.codesandbox.io/onboarding)

**Comment by Pagebakers** [comment]
There is likely a version mismatch. Updating @saas-ui/react and /form should resolve it.

**Comment by Pagebakers** [comment]
Which package manager and version are you using in the project by the way?

**Comment by waptik** [comment]
> Which package manager and version are you using in the project by the way?

yarn 3.2.0 I'm using a monorepo powered by turborepo

**Comment by waptik** [comment]
> There is likely a version mismatch. Updating @saas-ui/react and /form should resolve it.

I update both but still same error. I'll uninstall both and reinstall them again and see
![image](https://user-images.githubusercontent.com/1687551/178077135-88afbfe2-4c11-4289-a02b-fed8aa5d0b47.png)
![image](https://user-images.githubusercontent.com/1687551/178077170-c9549d8c-0d66-42b5-826a-eb23b3b2b270.png)

**Comment by Pagebakers** [comment]
This looks good 👌

I will try your example on my machine and get back to you shortly.

**Comment by Pagebakers** [comment]
These are the steps I followed.

1. git clone git@github.com:saas-js/saas-ui-nextjs-landing-page.git
2. Copy your code
4. yarn
5. yarn set version berry
6. yarn dev

And it's working as expected.

1. Check if `nodeLinker: node-modules` is configured in .yarnrc.yml
2. Delete the node_modules directory and reinstall.

This should definitely fix it.

**Comment by waptik** [comment]
> These are the steps I followed.
> 
> 1. git clone [git@github.com](mailto:git@github.com):saas-js/saas-ui-nextjs-landing-page.git
> 2. Copy your code
> 3. yarn
> 4. yarn set version berry
> 5. yarn dev
> 
> And it's working as expected.
> 
> 1. Check if `nodeLinker: node-modules` is configured in .yarnrc.yml
> 2. Delete the node_modules directory and reinstall.
> 
> This should definitely fix it.

I followed the same steps as you did and it works but another error pops up after form submission. It also shows up on the csb demo as well.

![image](https://user-images.githubusercontent.com/1687551/178104269-7555f8b2-1307-41c8-b3fe-299d4a1b5e91.png)

 After some time, I found the reason for that error. It was because the onSubmit function I added to `StepForm.onSubmit` wasn't async so after I added an async statement, the success alert message showed up. 

Following the steps below, the error regarding `useStepFormContext` has been fixed.
- [x] Check if `nodeLinker: node-modules` is configured in .yarnrc.yml
- [x] Delete the node_modules directory and reinstall.


![image](https://user-images.githubusercontent.com/1687551/178099839-0853d06c-8e7e-42df-b07a-65ed50977a63.png)
![image](https://user-images.githubusercontent.com/1687551/178156081-7b50fad1-fd51-4ad9-974a-ff3afa5b6256.png)

**Comment by Pagebakers** [comment]
> > These are the steps I followed.
> > 
> > 1. git clone [git@github.com](mailto:git@github.com):saas-js/saas-ui-nextjs-landing-page.git
> > 2. Copy your code
> > 3. yarn
> > 4. yarn set version berry
> > 5. yarn dev
> > 
> > And it's working as expected.
> > 
> > 1. Check if `nodeLinker: node-modules` is configured in .yarnrc.yml
> > 2. Delete the node_modules directory and reinstall.
> > 
> > This should definitely fix it.
> 
> I followed the same steps as you did and it works but another error pops up after form submission. It also shows up on the csb demo as well.
> 
> ![image](https://user-images.githubusercontent.com/1687551/178104269-7555f8b2-1307-41c8-b3fe-299d4a1b5e91.png)
> 
> After some time, I found the reason for that error. It was because the onSubmit function I added to `StepForm.onSubmit` wasn't async so after I added an async statement, the success alert message showed up.
> 
> Following the steps below, the error regarding `useStepFormContext` has been fixed.
> 
> * [x]  Check if `nodeLinker: node-modules` is configured in .yarnrc.yml
> * [x]  Delete the node_modules directory and reinstall.
> 
> ![image](https://user-images.githubusercontent.com/1687551/178099839-0853d06c-8e7e-42df-b07a-65ed50977a63.png) ![image](https://user-images.githubusercontent.com/1687551/178156081-7b50fad1-fd51-4ad9-974a-ff3afa5b6256.png)

Good that that's settled then!

You should get a type error when onSubmit isn't async / returning a promise.
Just checked but this is not the case, I'll open an new issue for this tomorrow.

**Comment by waptik** [comment]
> Good that that's settled then!
> 
> You should get a type error when onSubmit isn't async / returning a promise. Just checked but this is not the case, I'll open an new issue for this tomorrow.

Alright, looking forward to the fix.
