### ISSUE TITLE
NumberInput doesn't respect min/max attributes

### ISSUE THREAD

**Issue by iamclaytonray** [saas-js/saas-ui#69]
Setting min or max on the number input doesn't apply those rules. It should.

**Comment by Pagebakers** [comment]
Thanks for opening this issue Clayton!

I just tried to reproduce it, but both with NumberInput and Field it seems to be working here.

```ts
import { Field } from '@saas-ui/react'

<Field name="number" label="Number" type="number" min={1} max={10} />
```

```ts
import { NumberInput } from '@saas-ui/react'
<Number name="number" min={1} max={10}  />
```

https://user-images.githubusercontent.com/32583/179404511-83c8c1c7-5e83-48ac-ae01-36447f672bfe.mov

Could you give an example how you're using it?

**Comment by iamclaytonray** [comment]
Ahh, I was on a lower version (pre v1). It was probably broken then or something else. But works for me in a different app!
