### ISSUE TITLE
form irresponsive when using zod schema

### ISSUE THREAD

**Issue by waptik** [saas-js/saas-ui#77]
Hi.  

So i'm working on a new project and facing a weird issue when using the `Form` component and passing the `schema` props in the sense that the data inside console.log doesn't print when `schema` in `BaseForm` or `resolver` in `Form` is present but prints when `schema` or `resolver` has been omitted.

I extended the `Form` component by [configuring a default resolver](https://saas-ui.dev/docs/components/forms/form#configure-a-default-resolver) and created the `BaseForm.tsx` component as a result of that.

I have added reproduction code sample below

<details>
<summary>BaseForm.tsx</summary>

```tsx
// Add this somewhere in the root of your project.
import { zodResolver, zodFieldResolver } from "@saas-ui/forms/zod";
import { Form as BaseForm } from "@saas-ui/react";
import { ZodTypeAny } from "zod";

BaseForm.getResolver = (schema: ZodTypeAny) => zodResolver(schema); // @hookform/resolvers
BaseForm.getFieldResolver = (schema: ZodTypeAny) => zodFieldResolver(schema); // AutoForm field resolver

export default BaseForm;

```

</details>

<details>
<summary>NewProfileForm.tsx</summary>

```tsx
import { Box, Flex, InputLeftAddon, Text } from "@chakra-ui/react";
import { Button, Field, FormLayout, SubmitButton } from "@saas-ui/react";
import { z } from "zod";

import { APP_URL } from "~utils/constants";

import BaseForm from "../BaseForm";

const MyForm = () => {

  const schema = z.object({
    name: z.string(),
    username: z.string(),
    bio: z.string().optional(),
    gender: z.string(),
  });

  return (
    <>
     
      <BaseForm
        schema={schema}
        onSubmit={(data) => {
          //
          console.log("myForm.data", data);
        }}>
        <FormLayout>
          <FormLayout>
            <Field label="Your name" name="name" rules={{ required: "The name name field is required." }} />

            <Field
              label="Profile URL"
              _focus={{
                borderLeftWidth: "0px",
              }}
              leftAddon={<InputLeftAddon>{`${APP_URL}`}/s/</InputLeftAddon>}
              name="username"
              rules={{ required: "The username for your profile url cannot be empty" }}
            />
          </FormLayout>

          <FormLayout>
            <Field label="Your bio" type="textarea" name="bio" />
            <Field
              name="gender"
              label="Your gender"
              type="select"
              rules={{ required: true }}
              value="male"
              placeholder="Select one"
              options={[
                { value: "male", label: "Male" },
                { value: "female", label: "Female" },
              ]}
            />
          </FormLayout>
          <Box flexShrink={0} py={6}>
            <Flex experimental_spaceX={2} justify="space-between">
              <Button label="Cancel" />
              <SubmitButton w="full" />
            </Flex>
          </Box>
        </FormLayout>
      </BaseForm>
    </>
  );
};

export default MyForm;

```

</details>

----- Versions----
- @saas-ui/react: 1.3.2
- @saas-ui/forms: 1.3.2
- zod: 3.17.3 & 3.18.0
- react-hook-form: 7.34.2

**Comment by Pagebakers** [comment]
Thanks for reporting and the elaborate information. I will try to reproduce it.

**Comment by Pagebakers** [comment]
It looks like there is an error in the form, but it's not being rendered.

Can you add an `onError` handler and see if there is any validation errors?

**Comment by Pagebakers** [comment]
I tested with hook form 7.33.1 and the form is submitting, but only after selecting 'female' gender.

Can you add defaultValues to the form and try again?

```ts
<BaseForm
        schema={schema}
        defaultValues={{name: '', username: '', bio: '', gender:'male'}}
        onSubmit={(data) => {
          //
          console.log("myForm.data", data);
        }}>
```

The schema could also be improved:

```ts
const schema = z.object({
    name: z.string().min(1, { message: 'The name field is required' }),
    username: z.string().min(1, { message: 'The name field is required' }),
    bio: z.string().optional(),
    gender: z.enum(['male', 'female']),
  })
```

**Comment by waptik** [comment]
> It looks like there is an error in the form, but it's not being rendered.
> 
> Can you add an `onError` handler and see if there is any validation errors?

After adding `onError` and logging the errors in console, i found out that i used the name for a key in zod different from the field name. So after correcting that, the submitted values were now printing perfectly inside the console.

So the whole thing was because of a typo on my side. Thanks


> I tested with hook form 7.33.1 and the form is submitting, but only after selecting 'female' gender.
> 
> Can you add defaultValues to the form and try again?
> 
> ```ts
> <BaseForm
>         schema={schema}
>         defaultValues={{name: '', username: '', bio: '', gender:'male'}}
>         onSubmit={(data) => {
>           //
>           console.log("myForm.data", data);
>         }}>
> ```
> 
> The schema could also be improved:
> 
> ```ts
> const schema = z.object({
>     name: z.string().min(1, { message: 'The name field is required' }),
>     username: z.string().min(1, { message: 'The name field is required' }),
>     bio: z.string().optional(),
>     gender: z.enum(['male', 'female']),
>   })
> ```

Thanks for the tips on improving the schema, now i just have to remove the field rules as they stop having effect after the improvement.
