### ISSUE TITLE
The onChange property doesn't work in FormDialog Component

### ISSUE THREAD

**Issue by eliandersoh** [saas-js/saas-ui#83]
The onChange property doesn't work in FormDialog Component

```jsx
<FormDialog
    title="New post"
    {...disclosure}
    onChange={() => {
         console.log("This is not called")
    }}
    onSubmit={onSubmit}
>
</FormDialog>
```
The onChange is missed [here](https://github.com/saas-js/saas-ui/blob/38087ad21d52a6f211f3ddb732a95dd3b4a3fc06/packages/saas-ui-modals/src/form.tsx#L88) in form props destructuring.

**Comment by Pagebakers** [comment]
Thanks for reporting this 👍

Will get it solved asap.

**Comment by eliandersoh** [comment]
Thanks for the excellent library @Pagebakers. Let me know if you need any help in fixing it.

**Comment by Pagebakers** [comment]
If you have the time to create a PR to pass down onChange to the form that would be amazing 🙏

**Comment by eliandersoh** [comment]
I couldn't download the project's dependencies, so I couldn't test it, but I think it didn't break anything.
Can you check, please?

**Comment by Pagebakers** [comment]
Perfect, thanks for the fix! I will release it tomorrow.
