### ISSUE TITLE
SnackbarOptions type is not exported

### ISSUE THREAD

**Issue by jgillich** [saas-js/saas-ui#88]
`UseSnackbarOptions` as well. Would also be nice if `useSnackbar` had a return type (but I worked around it with `ReturnType<typeof useSnackbar>`

Relatively easy fix, if you want I can send you a PR soon(tm)

**Comment by Pagebakers** [comment]
Thanks for the head-ups.

I would really appreciate to receive a PR for this 🙏

**Comment by Pagebakers** [comment]
Will release a fix soon.

**Comment by jgillich** [comment]
Thanks! I wanted to get on this, but I've been busy with other things
