### ISSUE TITLE
formRef.current.setError not showing error message

### ISSUE THREAD

**Issue by waptik** [saas-js/saas-ui#90]
I have an input field of `type="text"` as a child of `Form` that i want to set  an error message after validating from the server.
When the value for the `slug` field changes, a request is made to the api to check the availability of the slug then it should display an error if the slug already exists.

Here's how i'm doing it

```tsx
  const formRef = useRef<UseFormReturn>(null);

<Form 
   ref={formRef}
   onChange={(data) => {
          setSlug(data.slug);
          console.log({ slugExist }); // slugExist is the returned value from the api server

          if (formRef.current) {
            formRef.current.setError(
              "slug",
              {
                type: "custom",
                message: slugExist === 1 ? "Slug already exists" : undefined,
              },
              { shouldFocus: true },
            );
          }
        }}
>

...

<Field name="slug" label="Slug" rules={{ required: true }} placeholder="a-store" />

```

**Comment by Pagebakers** [comment]
I think you are calling setError in the wrong place, you should call it in the callback function of the validation request to the server. 

Could you share the code of the validation request?

**Comment by waptik** [comment]
Where do you think i should put it? Inside a `useEffect` or `Field.onChange`?

The request is made using trpc's v10 `useQuery` hook to a server side router

```tsx
// components/form.tsx

// imports
import {useDebounce} from 'use-debounce';
import {trpc} from '~utils/trpc'
.....

 const [slug, setSlug] = useState("");
  const [debouncedSlug] = useDebounce(slug, 500);
  const [saving, setSaving] = useState(false);
  const { data: slugExist } = trpc.proxy.model.exists.useQuery(
    { slug },
    {
      enabled: debouncedSlug.length > 4,
    },
  );
```

Here's the full source code for the router.

```ts
// myrouter.ts
export const myrouter = t.router({
  exists: t.procedure
    .input(
      z.object({
        slug: z.string(),
      }),
    )
    .output(z.number())
    .query(async ({ ctx, input }) => {
      //
      const { prisma } = ctx;
      const { slug } = input;

      const store = await prisma.model.findUnique({
        where: { slug },
        select: {
          slug: true,
        },
      });

      return store ? 1 : 0;
    }),
});
```

I initially created a component wrapper for `<Field name="slug" label="Slug" rules={{ required: true }} placeholder="a-store" />` inside the same file where i tried to use `useFormContext` imported from `@saas-ui/react` but every object from the hook seem to be `undefined`. I followed your example at https://github.com/saas-js/saas-ui/discussions/51#discussioncomment-3021816

**Comment by Pagebakers** [comment]
I would recommend using the onSuccess and onError callbacks of useQuery.
